# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on: workflow_dispatch

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build_on_linux:
    # The type of runner that the job will run on
    #linux
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
      #下面的竖线表示要运行多行的命令
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          date
	  
  build_on_windows:
    runs_on: windows-latest
    steps:
      - name: run multi-line script  
        run: |  
          echo  "hellow github-actions "	
          Get-Date
